- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
- name: Install latest version of Apache2
  ansible.builtin.apt:
    name: apache2
    state: latest
- name: Autostart Apache
  service:
    name: apache2
    enabled: yes
    state: started
- name: Generate Apache configuration
  template:
    src: index.j2
    dest: /var/www/html/index.html
  notify: Restart apache2
